on:
  schedule:
    - cron: 34 10 11 * *
  repository_dispatch:
    types: [check-link]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

name: Broken Link Check
jobs:
  check:
    name: Broken Link Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Broken Link Check
        uses: technote-space/broken-link-checker-action@gh-actions
